diff -u -r zita-resampler-1.6.2.orig/apps/Makefile zita-resampler-1.6.2/apps/Makefile
--- zita-resampler-1.6.2.orig/apps/Makefile	2018-08-25 03:41:47.000000000 +0900
+++ zita-resampler-1.6.2/apps/Makefile	2019-04-02 22:17:15.239656924 +0900
@@ -23,9 +23,10 @@
 MANDIR ?= /usr/share/man/man1
 
 VERSION = 1.6.0
-CPPFLAGS += -MMD -MP -DVERSION=\"$(VERSION)\"
-CXXFLAGS += -O2  -ffast-math -Wall
+CPPFLAGS += -MMD -MP -DVERSION=\"$(VERSION)\" -I../source/
+CXXFLAGS += -ffast-math -Wall
 CXXFLAGS += -march=native
+LDFLAGS += -L../source/
 
 
 all:	zresample zretune zresample.1.gz zretune.1.gz
@@ -55,8 +56,8 @@
 
 
 install:	all
-	install -d $(BINDIR)
-	install -d $(MANDIR)
+	install -d $(DESTDIR)$(BINDIR)
+	install -d $(DESTDIR)$(MANDIR)
 	install -m 755 zresample $(DESTDIR)$(BINDIR)
 	install -m 755 zretune $(DESTDIR)$(BINDIR)
 	install -m 644 zresample.1.gz $(DESTDIR)$(MANDIR)
@@ -65,8 +66,8 @@
 uninstall: 
 	/bin/rm -f $(DESTDIR)$(BINDIR)/zresample
 	/bin/rm -f $(DESTDIR)$(BINDIR)/zretune
-	/bin/rm -f $(MANDIR)/zresample.1.gz
-	/bin/rm -f $(MANDIR)/zretune.1.gz
+	/bin/rm -f $(DESTDIR)$(MANDIR)/zresample.1.gz
+	/bin/rm -f $(DESTDIR)$(MANDIR)/zretune.1.gz
 
 clean:
 	/bin/rm -f *~ *.o *.a *.d *.so *.gz zresample zretune
diff -u -r zita-resampler-1.6.2.orig/source/Makefile zita-resampler-1.6.2/source/Makefile
--- zita-resampler-1.6.2.orig/source/Makefile	2018-08-25 03:41:47.000000000 +0900
+++ zita-resampler-1.6.2/source/Makefile	2019-04-02 22:17:33.403707245 +0900
@@ -32,7 +32,7 @@
 
 
 CPPFLAGS += -I. -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS
-CXXFLAGS += -Wall -fPIC -O2 -ffast-math
+CXXFLAGS += -Wall -fPIC -ffast-math
 CXXFLAGS += -march=native
 LDFLAGS += 
 LDLIBS +=
@@ -58,8 +58,8 @@
 	install -d $(DESTDIR)$(LIBDIR)
 	install -m 644 $(ZITA-RESAMPLER_H)   $(DESTDIR)$(INCDIR)/zita-resampler
 	install -m 755 $(ZITA-RESAMPLER_MIN) $(DESTDIR)$(LIBDIR)
-	ldconfig
 	ln -sf $(ZITA-RESAMPLER_MIN) $(DESTDIR)$(LIBDIR)/$(ZITA-RESAMPLER_SO)
+	ln -sf $(ZITA-RESAMPLER_MIN) $(DESTDIR)$(LIBDIR)/$(ZITA-RESAMPLER_MAJ)
 
 uninstall:
 	/bin/rm -rf $(DESTDIR)$(INCDIR)/zita-resampler
